name: Release
on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
      - name: Is Release Created
        run: |
          echo "release_created: ${{ steps.release.outputs.release_created }}"
          echo "releases_created: $${{ steps.release.outputs.releases_created }}"
